[book]
authors = ["Manish Goregaokar"]
language = "en"
multilingual = false
src = "src"
title = "The Diplomat Book"

[output.html.redirect]
"/intro.html" = "https://rust-diplomat.github.io/diplomat/"
"/user.html" = "https://rust-diplomat.github.io/diplomat/user"
"/basics.html" = "https://rust-diplomat.github.io/diplomat/basics"
"/types.html" = "https://rust-diplomat.github.io/diplomat/types"
"/opaque.html" = "https://rust-diplomat.github.io/diplomat/opaque.html"
"/structs.html" = "https://rust-diplomat.github.io/diplomat/structs.html"
"/option.html" = "https://rust-diplomat.github.io/diplomat/option.html"
"/result.html" = "https://rust-diplomat.github.io/diplomat/result.html"
"/writeable.html" = "https://rust-diplomat.github.io/diplomat/writeable.html"
"/docs.html" = "https://rust-diplomat.github.io/diplomat/docs.html"
"/lifetimes.html" = "https://rust-diplomat.github.io/diplomat/lifetimes.html"
"/abi.html" = "https://rust-diplomat.github.io/diplomat/abi.html"
"/attrs.html" = "https://rust-diplomat.github.io/diplomat/attrs.html"
"/attrs/disable.html" = "https://rust-diplomat.github.io/diplomat/attrs/disable.html"
"/attrs/rename.html" = "https://rust-diplomat.github.io/diplomat/attrs/rename.html"
"/attrs/namespace.html" = "https://rust-diplomat.github.io/diplomat/attrs/namespace.html"
"/attrs/constructors.html" = "https://rust-diplomat.github.io/diplomat/attrs/constructors.html"
"/attrs/iterators.html" = "https://rust-diplomat.github.io/diplomat/attrs/iterators.html"
"/attrs/accessors.html" = "https://rust-diplomat.github.io/diplomat/attrs/accessors.html"
"/attrs/indexing.html" = "https://rust-diplomat.github.io/diplomat/attrs/indexing.html"
"/attrs/comparators.html" = "https://rust-diplomat.github.io/diplomat/attrs/comparators.html"
"/attrs/stringifiers.html" = "https://rust-diplomat.github.io/diplomat/attrs/stringifiers.html"
"/safety.html" = "https://rust-diplomat.github.io/diplomat/safety.html"
"/developer.html" = "https://rust-diplomat.github.io/diplomat/developer.html"
"/demo_gen/intro.html" = "https://rust-diplomat.github.io/diplomat/demo_gen/intro.html"
"/demo_gen/quickstart.html" = "https://rust-diplomat.github.io/diplomat/demo_gen/quickstart.html"
"/demo_gen/attributes.html" = "https://rust-diplomat.github.io/diplomat/demo_gen/attributes.html"
"/demo_gen/markup.html" = "https://rust-diplomat.github.io/diplomat/demo_gen/markup.html"
"/demo_gen/renderer.html" = "https://rust-diplomat.github.io/diplomat/demo_gen/renderer.html"
"/demo_gen/custom_renderer.html" = "https://rust-diplomat.github.io/diplomat/demo_gen/custom_renderer.html"
"/demo_gen/custom_functions.html" = "https://rust-diplomat.github.io/diplomat/demo_gen/custom_functions.html"
"/index.html" = "https://rust-diplomat.github.io/diplomat/"